apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  namespace: elastic-system
spec:
  storageClassName: elasticsearch-data-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/elasticsearch-volume/data"
