apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.6.1
  count: 1
  elasticsearchRef:
    name: "elasticsearch"
  http:
    service:
      metadata:
        annotations:
          metallb.universe.tf/address-pool: kibana-pool
      spec:
        type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        # foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
